### ISSUE TITLE
Update To essential 3.x (mysql => couchDb) 

### ISSUE THREAD

**Issue by Xtrem65** [PandaBasketteur/Paycheck#3]
Hi, as you probably know, essential mod 3.x is now out and includes several big changes (including used database).

CouchDB replaces mySQL.

Have you planned to update this mod too ?

Thanks,
(Keep up the good work).

**Comment by Alex-Bumblebee** [comment]
Hello,

No I will not do it, simply because I would not go to 3.0 I do not really see the use for my server for now :)
